name: Github actions
run-name: ${{ github.actor }} is testing Github actions
on:
  push:
    branches:
      - '*'

jobs:
  build-test-image-container:
    name: Build and test docker
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Set up Docker Compose
      run: |
        DOCKER_COMPOSE_VERSION=2.15.1
        sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Verify Docker installation
      run: |
        docker --version
        docker-compose --version

     - name: Building docker image
      run: sh script.sh build-image

    - name: Start docker container
      run: sh script.sh start

    - name: Generate documetation
      run: sh script.sh generate-documentation

    - name: Stop docker container
      run: sh script.sh stop
